const QUESTS = {
  building: {
    title: "Building",
    subtitle: "The hearth becomes a citadel.",
    quests: [
      q("Hearth Claim", "Choose the heart of the future settlement and mark where the first hall will stand.", ["Walk the nearby area and choose the place where your long-term base will be built.", "Make sure it has room for expansion, nearby wood and stone, and a safe way back before dark.", "Mark the center with a campfire, pillar, torches, or banner.", "Clear the immediate ground so the first shelter can begin there."], "Pick somewhere practical first. Flat ground near trees, water, and surface stone is better than a dramatic place that is hard to defend.", "Surveyor's Kit", ["/give @p torch 16", "/give @p oak_log 16", "/give @p bread 8"]),
      q("First Shelter", "Raise the first refuge before the wilderness claims the night.", ["Build a basic enclosed shelter at your claimed hearth.", "Add walls, a roof, and one door or protected entrance.", "Make room inside for a bed and survival supplies.", "Be able to survive the first night safely inside it."], "Dirt is acceptable for the first night, but wood or stone is better if you can gather it quickly.", "Settler's Bundle", ["/give @p oak_planks 32", "/give @p torch 16", "/give @p bread 8"]),
      q("Storehouse Corner", "Order is the first sign that a camp is becoming a home.", ["Place at least 3 chests inside or beside the shelter.", "Separate food, tools, and building blocks into different storage.", "Keep the storage area lit.", "Make sure you can reach supplies quickly in an emergency."], "Even simple organization makes hardcore survival much safer.", "Quartermaster's Gift", ["/give @p chest 3", "/give @p item_frame 3", "/give @p torch 12"]),
      q("Fire and Light", "Darkness is an enemy. Light is a claim upon the land.", ["Light the inside of the shelter so hostile mobs cannot spawn there.", "Light the entrance and nearby walking space outside.", "Remove obvious dark pockets around the base.", "Be able to step outside at night without immediate danger."], "Focus on the doorway, corners, and any holes or ledges nearby.", "Lamplighter's Cache", ["/give @p torch 32", "/give @p coal 16"]),
      q("The Great Hall Foundation", "The rough shelter must become the beginning of a true hall.", ["Expand the shelter into a larger main room.", "Make clear places for sleeping, crafting, and storage.", "Improve the walls or roof so it looks more intentional than temporary.", "Keep the entire structure safe and lit."], "This is the point where the base stops being temporary.", "Hallwright's Supplies", ["/give @p oak_log 24", "/give @p oak_planks 48", "/give @p lantern 4"]),
      q("Secure the Camp", "A wise ruler fortifies before decorating.", ["Mark the edge of your immediate base area.", "Add a fence, trench, wall, raised edge, or other defensive boundary.", "Create one clear entry point that you can defend.", "Light the approach to that entry point."], "You do not need a massive wall yet. Even a modest perimeter helps.", "Warden's Materials", ["/give @p cobblestone 64", "/give @p torch 16", "/give @p oak_fence 24"]),
      q("Lantern Road", "Roads bind a settlement together as surely as walls.", ["Choose two important places in the base, such as hall, farm, mine, smithy, or dock.", "Build a path between them using one consistent style.", "Light the path with torches, lanterns, or campfires.", "Make the route safe enough to walk at night."], "Even a short road makes the whole base feel more like one settlement.", "Roadmaker's Stock", ["/give @p lantern 6", "/give @p gravel 32", "/give @p cobblestone 32"]),
      q("Walls of the Hearth", "The hearth deserves a boundary worthy of defense.", ["Expand the camp perimeter into a stronger town boundary.", "Build a more complete wall, fence line, or barrier.", "Add a gate or guarded entrance.", "Check that the wall links properly around the vulnerable edges."], "This wall does not need to be beautiful yet. It needs to keep the town feeling protected.", "Mason's Wages", ["/give @p stone_bricks 48", "/give @p cobblestone_wall 24", "/give @p torch 16"]),
      q("The Smithy Quarter", "No town can thrive without iron, flame, and tools in one place.", ["Choose a spot near the hall for a smithy or workshop wing.", "Build a room or yard for furnaces and metalworking.", "Place furnaces, ore storage, and tool storage there.", "Give it a distinct visual style so it feels like its own quarter."], "A smithy looks good with stone, brick, metal, or darker wood accents.", "Forgekeeper's Crate", ["/give @p iron_ingot 16", "/give @p coal 24", "/give @p blast_furnace 1"]),
      q("Granary and Cellar", "A true town stores for winter, famine, and war.", ["Build a food storage room, pantry, cellar, or granary.", "Place barrels or chests for crops and cooked food.", "Move your food stock into that district.", "Decorate it so it feels like part of the settlement economy."], "Put this near fields, kitchen space, or the hall.", "Steward's Stores", ["/give @p barrel 4", "/give @p bread 16", "/give @p hay_block 12"]),
      q("Garden Court", "Beauty gives people a reason to endure hardship.", ["Pick an empty patch inside the settlement.", "Turn it into a courtyard, pond, herb patch, or decorative garden.", "Use at least 3 decorative materials, such as flowers, leaves, moss, or stone detail.", "Connect it to existing roads or entrances."], "A small beautiful space can make the base feel alive.", "Gardener's Satchel", ["/give @p flowering_azalea 2", "/give @p moss_block 16", "/give @p lantern 2"]),
      q("Library of Maps", "Roads are remembered by those who keep records.", ["Build a library, archive, or map room attached to the main base.", "Place bookshelves, storage, or lecterns inside it.", "Display at least one map, banner, or sign-based record.", "Reserve space for future exploration records."], "This room becomes much better later if you keep adding maps to it.", "Scholar's Chest", ["/give @p bookshelf 6", "/give @p lectern 1", "/give @p map 1", "/give @p paper 16"]),
      q("Stable of the North Road", "Long roads demand mounts, tack, and shelter.", ["Build a stable, paddock, or travel yard on one edge of the town.", "Include a place for at least one animal or future mount.", "Add storage for travel supplies and food.", "Connect the stable to a main road."], "Put the stable near the direction you most often travel.", "Stablemaster's Kit", ["/give @p saddle 1", "/give @p hay_block 16", "/give @p chest 1"]),
      q("Copper Workshop", "The town begins to show prosperity when craft becomes art.", ["Gather copper or use copper already stored.", "Build a workshop, roof section, tower top, or decorative wing with copper detail.", "Make sure it still matches the overall town style.", "Use the new structure as a real part of the settlement, not a disconnected decoration."], "Even a small amount of copper can make a build feel more advanced.", "Tinker's Treasury", ["/give @p copper_block 16", "/give @p lightning_rod 4", "/give @p lantern 4"]),
      q("The Villager Ward", "A settlement becomes a town when it shelters more than one soul.", ["Build a protected district for villagers.", "Add beds and at least one useful workstation.", "Make sure hostile mobs cannot easily enter at night.", "Keep the area fully lit and reachable from the rest of the base."], "The villager ward should feel like a defended neighborhood.", "Town Charter", ["/give @p bed 4", "/give @p bread 16", "/give @p bell 1"]),
      q("Portal Wing", "Nether access should be a gate of purpose, not a hole in the ground.", ["Choose a proper place for Nether travel.", "Build a portal room, archway, or gatehouse.", "Add safe walking space, storage, and lighting around it.", "Make the portal feel like part of the town plan."], "Keep flammables and cramped corners away from the portal area.", "Embergate Provision", ["/give @p obsidian 10", "/give @p flint_and_steel 1", "/give @p fire_charge 4"]),
      q("Harbor Steps", "Water is a road for those wise enough to use it.", ["Find the nearest river, lake, or sea edge linked to your settlement.", "Build steps, a dock, or a landing.", "Add at least one storage point for water travel or fishing gear.", "Connect the harbor to town paths."], "Even a small dock makes future travel feel intentional.", "Riverman's Bundle", ["/give @p oak_boat 1", "/give @p lantern 4", "/give @p barrel 2"]),
      q("Greenhouse Wing", "Delicate growth deserves shelter from frost and misfortune.", ["Build an enclosed farm room or greenhouse.", "Place crops inside it.", "Add lighting and water so it is functional.", "Blend it into the town rather than leaving it isolated."], "Glass, wood, and stone make an easy greenhouse palette.", "Glassgrower's Cache", ["/give @p glass 32", "/give @p dirt 16", "/give @p water_bucket 1"]),
      q("Kennel of Companions", "Loyal beasts deserve a place at the edge of the hall.", ["Build a kennel, pen, or companion corner.", "Include shelter, flooring, and access from a path.", "Add storage for food or supplies.", "Keep the enclosure safe from night danger."], "This works for wolves, cats, or decorative stable companions.", "Houndkeeper's Gift", ["/give @p bone 8", "/give @p cooked_beef 8", "/give @p carpet 4"]),
      q("Trial Hall Annex", "Let trophies and hard-won spoils become part of the town's memory.", ["Build a trophy room, armory, or war annex.", "Add armor stands, banner space, or item displays.", "Keep storage for combat loot or dungeon supplies there.", "Display at least one meaningful object from an expedition."], "This room becomes more fun the more adventures you survive.", "Relickeeper's Chest", ["/give @p armor_stand 2", "/give @p item_frame 4", "/give @p white_banner 2"]),
      q("Archaeologist's Yard", "Ancient fragments deserve study, not a random chest.", ["Build a relic yard, dig shed, or archaeology room.", "Add shelves, pots, or display pedestals.", "Create storage for brushes, pottery shards, or suspicious block finds.", "Place at least one decorative relic display."], "This room pairs well with maps, signs, and pots.", "Dust-Seeker's Crate", ["/give @p brush 1", "/give @p decorated_pot 2", "/give @p chest 1"]),
      q("Hall of Maps and Banners", "Every frontier town should proclaim where it has been and what it has survived.", ["Expand your map room or build a dedicated hall for travel records.", "Hang at least two maps, banners, or route markers.", "Add a display for named expeditions or known landmarks.", "Make the hall feel like a civic record of the settlement."], "Use signs to name regions, roads, or dangers.", "Chronicler's Award", ["/give @p map 2", "/give @p white_banner 2", "/give @p glow_item_frame 2"]),
      q("Copper Clocktower", "A skyline landmark gives the town identity and warning alike.", ["Build a tower taller than the surrounding structures.", "Use copper or other advanced detail on the upper section.", "Add a lit top, bell, or signal point.", "Make sure it can be safely reached from the ground."], "A good tower becomes the visual symbol of the settlement.", "Watchmaker's Grant", ["/give @p copper_block 24", "/give @p bell 1", "/give @p lantern 6"]),
      q("Sky Dock", "The upper reaches of the settlement should be ready for lookout duty and future travel.", ["Choose a high point in or above the base.", "Build a platform, terrace, or elevated landing area.", "Connect it safely with stairs, scaffolding, or protected climbing.", "Add rails, lighting, and storage."], "Think of this as both lookout and prestige structure.", "Highroad Supply", ["/give @p scaffolding 16", "/give @p lantern 6", "/give @p chest 1"]),
      q("Sculk-Sealed Vault", "Deep relics and dangerous treasures require a chamber of secrecy.", ["Choose a secure location for rare items.", "Build a hidden, fortified, or isolated vault room.", "Add doors, locks, or redstone-style access if desired.", "Move your rarest loot into the vault."], "This is the symbolic late-game treasure room.", "Vaultwarden's Seal", ["/give @p iron_door 2", "/give @p redstone_torch 4", "/give @p diamond 1"]),
      q("Pale Garden Watchpost", "A road into eerie lands should be watched and warded.", ["Choose the outer edge of your territory facing a dangerous region.", "Build a watchpost, guard hut, or outlying gate.", "Link it back to town with a safe route or marked path.", "Add lighting and supplies for a return stop."], "This should feel like a frontier post, not a second town.", "Sentinel's Store", ["/give @p campfire 2", "/give @p lantern 4", "/give @p spruce_log 24"]),
      q("Pale Gate Chapel", "Let the edge of the realm bear a solemn shrine against darkness.", ["Build a shrine, chapel, or memorial near a gate or road edge.", "Use pale, mossy, or quiet decorative materials if possible.", "Add candles, benches, or symbolic detail.", "Make the structure feel intentional and solemn."], "This quest is about mood as much as function.", "Warden Chapel Fund", ["/give @p candle 8", "/give @p quartz_block 16", "/give @p lantern 4"]),
      q("Citadel Crown", "The final mark of mastery is a structure that declares the settlement complete.", ["Choose the final prestige project for the base.", "Build a keep roofline, monument, central tower crown, or similar capstone structure.", "Make it visible from the rest of town.", "Finish it as a statement that the settlement has become a citadel."], "This is your end of the building path landmark.", "Lord's Treasury", ["/give @p diamond 3", "/give @p emerald 6", "/give @p copper_block 16"])
    ]
  },
  gathering: {
    title: "Gathering",
    subtitle: "The storehouse fills before the banners rise.",
    quests: [
      q("The First Stores", "Before glory comes stockpile.", ["Gather basic wood, stone, and fuel.", "Bring the materials back to the shelter.", "Store them instead of carrying everything at once.", "Keep a small emergency supply ready."], "Early survival is safer when the base already has extra materials.", "Pioneer's Wage", ["/give @p bread 12", "/give @p torch 16", "/give @p chest 1"]),
      q("Bread for the Hall", "A warm hall is meaningless if the table is bare.", ["Gather enough food for several nights.", "Cook or prepare it into a usable reserve.", "Put the food into storage at the base.", "Keep some on your person for emergencies."], "Bread, cooked meat, or early farm crops all count.", "Baker's Due", ["/give @p bread 16", "/give @p wheat 24"]),
      q("Timber Tithe", "The forest pays the first tax to every new settlement.", ["Chop enough logs for future building work.", "Bring the logs safely back to the base.", "Replant saplings if you can.", "Store the wood for building, not just tools."], "Gather extra now so the first hall expansion is easier later.", "Woodcutter's Thanks", ["/give @p oak_log 24", "/give @p torch 8"]),
      q("Stone for the Hearth", "Timber raises a camp. Stone raises a future.", ["Mine stone or cobblestone close to the base.", "Bring back enough for walls, paths, or furnaces.", "Store the stone in your building materials chest.", "Leave yourself with a reserve for the next project."], "Surface stone, shallow cave stone, or smelted stone all fit the spirit.", "Quarryman's Pay", ["/give @p cobblestone 48", "/give @p coal 12"]),
      q("Fields of Plenty", "The land nearest the hall should feed the hall.", ["Plant at least one small crop field near the base.", "Use water so the field can regrow properly.", "Harvest enough crops to matter.", "Store the harvest in food storage."], "Wheat, potatoes, and carrots make a strong early farm set.", "Farmer's Blessing", ["/give @p wheat_seeds 16", "/give @p carrot 12", "/give @p potato 12"]),
      q("Iron for the Forge", "Every useful thing in early survival asks for iron.", ["Go mining specifically for iron.", "Return alive with the ore or raw iron.", "Smelt it or store it in the smithy supplies.", "Keep enough iron for future tools and gear."], "Do not spend it all immediately. The point is building stock.", "Smith's Wages", ["/give @p iron_ingot 12", "/give @p coal 16"]),
      q("Glassmaker's Burden", "Sand becomes windows, lantern frames, and civilized ambition.", ["Gather a useful amount of sand.", "Smelt it into glass.", "Store the glass for a future building quest.", "Keep at least some of it unused for later."], "This quest supports greenhouse, windows, and decorative upgrades.", "Glazier's Purse", ["/give @p glass 24", "/give @p coal 12"]),
      q("Leather and Reed", "Books, maps, and knowledge begin in humble materials.", ["Gather leather from animals.", "Harvest or grow sugar cane.", "Bring both back to storage.", "Keep them ready for books, maps, or library work."], "This prepares you for map room and enchantment progress.", "Scribe's Bundle", ["/give @p leather 8", "/give @p sugar_cane 24", "/give @p paper 12"]),
      q("River Reed Contract", "A steward who neglects paper neglects the memory of the realm.", ["Find a riverbank or water edge near home.", "Harvest a larger sugar cane supply.", "Replant enough cane to keep the source growing.", "Store paper-making materials in the scholar quarter."], "This is your long-term map and book supply quest.", "Recordkeeper's Roll", ["/give @p paper 24", "/give @p sugar_cane 24"]),
      q("Beekeeper's Tithe", "Honey and flowers soften a hard life and serve more than beauty.", ["Find bees or a bee nest.", "Collect honey bottles or honeycomb safely.", "Bring back flowers or related decorative goods.", "Store the products in food, garden, or trade storage."], "Campfires help when working around bees.", "Apiarist's Share", ["/give @p honey_bottle 3", "/give @p honeycomb 6"]),
      q("Mounted Provisioning", "Long travel begins with simple preparation.", ["Gather travel food for expeditions.", "Bring back leather, hay, or stable-friendly materials.", "Store them in the stable or road supplies chest.", "Leave the base better prepared for future journeys."], "This supports road and mount-themed quests later.", "Roadwarden's Pouch", ["/give @p cooked_beef 12", "/give @p hay_block 8", "/give @p leather 4"]),
      q("The Copper Cache", "The town enters a richer age when copper enters the ledger.", ["Mine enough copper to matter.", "Smelt it into ingots.", "Store it in building stock.", "Keep it reserved for decorative or advanced construction."], "Copper is best used as future town material, not wasted immediately.", "Tinker's Fee", ["/give @p copper_ingot 24", "/give @p coal 12"]),
      q("Wool for the Hall", "Comfort is not weakness when winter comes.", ["Gather wool through sheep, shears, or dyes.", "Bring back enough for decoration, beds, or banners.", "Store it separately from stone and wood.", "Keep a small cloth reserve for future building interiors."], "A base feels much more settled once interiors use wool or banners.", "Weaver's Gift", ["/give @p white_wool 16", "/give @p red_wool 8"]),
      q("Spring to Life Harvest", "Bring home flowers, leaves, and wild beauty from nearby lands.", ["Travel to another nearby biome.", "Gather at least three decorative natural materials.", "Return them safely to base.", "Store them for landscaping or garden work."], "Moss, flowers, leaves, and saplings all help the town look more alive.", "Herbalist's Satchel", ["/give @p moss_block 16", "/give @p azalea 2", "/give @p flowering_azalea 2"]),
      q("Glow Berry Descent", "Caves hide living lanterns for those willing to descend.", ["Find a lush cave or cave-vine source.", "Gather glow berries and any useful cave greenery.", "Return to base alive.", "Store the haul for gardens, kitchens, or hall decoration."], "This quest is a cave run with decorative purpose.", "Cavern Tender's Prize", ["/give @p glow_berries 16", "/give @p moss_block 12"]),
      q("Deep Quarry", "Great walls demand greater stone.", ["Mine a large bulk supply of stone, deepslate, or masonry material.", "Bring the full haul back in one or more safe trips.", "Sort the materials into building stock.", "Keep enough available for major projects."], "This is your big construction reserve quest.", "Mason's Dividend", ["/give @p stone 64", "/give @p andesite 32"]),
      q("Glow in the Dark", "The larger the town, the more light it devours.", ["Gather coal, sticks, lantern materials, or other lighting resources.", "Craft at least a substantial batch of light sources.", "Store them in the base for future defenses and roads.", "Keep your settlement ready for expansion."], "Running out of light is one of the easiest ways to make a town unsafe.", "Lightbearer's Cache", ["/give @p torch 32", "/give @p lantern 6", "/give @p coal 24"]),
      q("Pearls for the Future", "The wise keep part of their gaze turned toward the End.", ["Prepare food and safe return supplies.", "Hunt or gather ender pearls, or similar rare progression loot.", "Return alive.", "Store the pearls in a vault or rare-goods chest."], "This quest is about long-term progression readiness.", "Wayfarer's Token", ["/give @p ender_pearl 2", "/give @p golden_carrot 8"]),
      q("Armadillo Scute Run", "Loyal companions deserve more than courage alone.", ["Travel to a savanna or badlands biome.", "Find at least one armadillo.", "Collect scutes from the journey.", "Return the scutes to your kennel, vault, or smithy storage."], "Think of this as a specialty material expedition for companion gear.", "Beastwarden's Satchel", ["/give @p armadillo_scute 6", "/give @p bone 6"]),
      q("Pottery Shard Hunt", "Dust and buried memory are treasure to patient hands.", ["Craft or bring a brush.", "Travel to an archaeology site.", "Find suspicious sand or suspicious gravel.", "Brush at least one suspicious block without breaking it.", "Return with a shard, relic, or archaeology item."], "Desert wells, desert temples, trail ruins, and some ocean ruins are good targets.", "Antiquarian's Purse", ["/give @p brush 1", "/give @p decorated_pot 1", "/give @p emerald 2"]),
      q("Trial Chamber Provisions", "No delver should descend into danger with a half-packed kit.", ["Prepare strong food, arrows, blocks, and spare tools.", "Create a dedicated expedition chest or travel loadout.", "Leave enough reserve gear at home in case of loss.", "Finish with a proper dungeon-ready kit."], "This is not the chamber run itself. It is the preparation that makes it survivable.", "Delver's Loadout", ["/give @p arrow 24", "/give @p cooked_beef 12", "/give @p cobblestone 32"]),
      q("Tuff and Copper Reserve", "Richer architecture begins in deeper strata.", ["Gather tuff and copper from underground exploration.", "Bring both resources back alive.", "Store them in building stock.", "Keep them reserved for advanced construction."], "This supports your more impressive mid-late building quests.", "Stonewright's Grant", ["/give @p tuff 32", "/give @p copper_block 8"]),
      q("Sculk Sample Recovery", "Bring back the strange growth of the deep without becoming part of it.", ["Prepare for a dangerous underground run.", "Reach a sculk-rich area.", "Gather sculk blocks or related deep materials.", "Escape and return with the sample haul."], "This is a tense extraction quest, not a long stay.", "Deep Scholar's Fee", ["/give @p sculk 16", "/give @p diamond 1"]),
      q("Breeze-Proof Supplies", "Strange new dangers demand sensible preparation.", ["Gather shield, food, arrows, and spare equipment.", "Build a reliable dungeon loadout meant for knockback-heavy combat.", "Store that loadout in one place.", "Keep it ready for Trial Chamber work."], "This is another prep quest, but more specialized than the earlier chamber provisions quest.", "Chamberrunner's Bag", ["/give @p shield 1", "/give @p arrow 24", "/give @p cooked_beef 12"]),
      q("Fisher's Tribute", "Rivers and coasts should feed the hall as surely as fields.", ["Go on a proper fishing or shoreline supply trip.", "Bring back useful fish or water-related loot.", "Store the catch in food or harbor supplies.", "Leave the settlement better prepared for waterside life."], "This quest fits especially well once you have a dock.", "Rivertithe", ["/give @p cooked_cod 10", "/give @p salmon 6", "/give @p fishing_rod 1"]),
      q("Vaultkeeper's Reserve", "The settlement now keeps not just supplies, but emergency wealth.", ["Gather rare goods such as diamonds, emeralds, pearls, or advanced food.", "Return and store them in the vault.", "Keep them as reserve wealth, not daily use items.", "Turn the base into a place with true strategic surplus."], "This is your final economic maturity quest.", "Treasury Allotment", ["/give @p diamond 2", "/give @p emerald 4", "/give @p golden_carrot 8"])
    ]
  },
  pathfinder: {
    title: "Pathfinder",
    subtitle: "The frontier opens under steady feet.",
    quests: [
      q("A Place to Call Home", "Before walls are raised, a survivor must choose where to stand.", ["Explore the nearby region.", "Find a base location that is practical, defensible, or beautiful enough to commit to.", "Mark that location so you can return to it reliably.", "Get back safely with the choice made."], "Near water, wood, and open building room is ideal.", "Wayfinder's Start", ["/give @p compass 1", "/give @p bread 8", "/give @p torch 12"]),
      q("Scout the Perimeter", "Learn the land before the land teaches you the hard way.", ["Walk the area surrounding the chosen base location.", "Identify nearby wood, stone, water, and food sources.", "Notice nearby caves, cliffs, or hostile danger spots.", "Return to base with a clear idea of the immediate terrain."], "This quest is about knowledge, not loot.", "Ranger's Notes", ["/give @p map 1", "/give @p torch 12"]),
      q("Night Watch", "The first enemies should fall before they ever touch the walls.", ["Wait until night near the base.", "Patrol the outer edge of your settlement.", "Defeat several hostile mobs near your territory.", "Return inside safely before the situation becomes reckless."], "Stay near home. This is defense, not a midnight expedition.", "Watchman's Share", ["/give @p arrow 16", "/give @p shield 1"]),
      q("The Road Beyond", "The future of the town lies beyond what it can already see.", ["Leave the base with food, torches, and a way to mark the path.", "Travel far enough to discover a new biome, landmark, or notable resource area.", "Mark the way with signs, torches, pillars, or a map note.", "Return alive with knowledge or one useful find."], "This is your first true scouting quest.", "Scout's Wage", ["/give @p compass 1", "/give @p cooked_beef 10", "/give @p torch 16"]),
      q("Trial by Bow", "A wise fighter kills from range whenever possible.", ["Bring a bow or crossbow and spare ammunition.", "Fight hostile mobs at range instead of rushing into melee.", "Defeat several enemies this way.", "Return with arrows or proof you kept control of the fight."], "Skeletons, zombies in open terrain, and creepers at distance are good targets.", "Archer's Due", ["/give @p bow 1", "/give @p arrow 24"]),
      q("Tower Signal", "A marked lookout turns wilderness into known frontier.", ["Travel to a hill, ridge, or visible landmark.", "Build a small signal marker, campfire post, or torch pillar.", "Make the location easy to recognize from a distance.", "Return to town alive."], "This helps future journeys feel like part of an expanding road network.", "Beaconer's Kit", ["/give @p torch 16", "/give @p campfire 2", "/give @p cobblestone 16"]),
      q("Crypt Cleanse", "Dangerous hollows near the town should be cleared before they fester.", ["Find a nearby cave pocket, dungeon, ruin, or hostile site.", "Enter prepared with food, torches, and a retreat route.", "Clear the threat or loot one meaningful gain.", "Return alive with the area no longer an immediate menace."], "Do not go deeper than you can safely escape.", "Delver's Reward", ["/give @p iron_ingot 12", "/give @p bread 10", "/give @p torch 16"]),
      q("Protect the Villagers", "The strong are measured by who survives under their watch.", ["Count or confirm the villagers you intend to protect before nightfall.", "Light the villager district and close obvious entry gaps.", "Stay in or near the village through the night.", "Kill hostile mobs threatening the area.", "Confirm the villagers survive until morning."], "Think of this as a full night defense quest.", "Guardian's Mark", ["/give @p shield 1", "/give @p emerald 3", "/give @p bread 12"]),
      q("Saddle the Frontier", "Search for safer, longer travel and the means to ride it.", ["Travel in the main direction you expect future expansion.", "Search for a useful road line, mount source, or travel advantage.", "Bring back one gain for the stable or road network.", "Mark the route for later return."], "This can be about route scouting as much as the mount itself.", "Rider's Due", ["/give @p saddle 1", "/give @p hay_block 8"]),
      q("The Monstrous Shore", "Coasts promise wealth and ambush in equal measure.", ["Travel to a river mouth, coast, or ocean edge.", "Survive the dangers there, whether drowned, terrain, or distance.", "Bring back fish, treasure, or a useful harbor location.", "Return with enough information to justify future harbor work."], "This is a scouting-and-survival shoreline quest.", "Mariner's Purse", ["/give @p cooked_cod 8", "/give @p oak_boat 1", "/give @p compass 1"]),
      q("Pale Garden Foray", "Eerie woods test the nerve more than the blade.", ["Prepare food, torches, and an easy path home.", "Travel into an eerie or dangerous forest region.", "Gather one atmospheric or rare material from the trip.", "Return to base alive with route knowledge."], "This is a fear-and-discipline quest, not a full conquest.", "Forester's Oath", ["/give @p lantern 4", "/give @p cooked_beef 10", "/give @p ender_pearl 1"])
    ]
  }
};

function q(title, description, objectives, hint, reward, commands) {
  return { title, description, objectives, hint, reward, commands };
}
